config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :users
  get 'home/top' => 'home#top'
  get 'home/about' => "home#about", as: "about"
  root to: "home#top"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def edit
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/home/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class=px-3 mx-auto>
     "Welcome to"
     <i class="fas fa-book"></i>
     <strong>Bookers</strong>
     "!"
    </h1>
  </div>
</div>

app/views/home/top.html.erb
<%if flash[:notice] %>
 <p id="notice">
   <%= flash[:notice] %>
 </p>
 <% end %>
 <p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        "Welcome to"
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        "!!"
      </h1>
      <p>
        "In"
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        ","
      </p>
      <p>
        you can share and exchange your opinions,inpressions, and emotions
      </p>
    </div>
  </div>
  <div class="btn-wrapper col-10 mx-auto">
    <div class="row">
      <%= link_to "Log in", new_user_session_path, class: "btn btn-info" %>
    </div>
    <div class="row">
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/4f3d4442e3.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                         aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="toggle navigation">
            <span class="navbar-toggle-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Home", home_top_path %>
              </li>
              <li class="nav-item">
                <%= link_to "User", users_path %>
              </li>
              <li class="nav-item">
                <%= link_to "Books", books_path %>
              </li>
              <li class="nav-item">
                <%= link_to "Log out", home_top_path, method: :delete %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Home", home_top_path %>
              </li>
              <li class="nav-item">
                <%= link_to "About", about_path %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path %>
              </li>
              <li class="nav-item">
                <%= link_to "Log in", new_user_session_path %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>